"""The control plane. SQLite now; a shared Postgres at more than one VM (4.2)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class Tenant:
    id: str
    sub: str
    email: str
    timezone: str
    status: str
    project_id: int
    created_at: float


class ControlStore(Protocol):
    def create_tenant(self, *, sub: str, email: str, timezone: str) -> Tenant: ...
    def tenant_by_sub(self, sub: str) -> Tenant | None: ...
    def tenant_by_id(self, tenant_id: str) -> Tenant | None: ...
    def tenant_by_email(self, email: str) -> Tenant | None: ...
    def set_status(self, tenant_id: str, status: str) -> None: ...
    def set_timezone(self, tenant_id: str, timezone: str) -> None: ...
    def create_session(self, *, tenant_id: str, value: str, expires_at: float) -> None: ...
    def session_tenant(self, value: str, now: float) -> str | None: ...
    def delete_sessions(self, tenant_id: str) -> None: ...
    def issue_token(self, tenant_id: str) -> str: ...
    def revoke_tokens(self, tenant_id: str) -> None: ...
    def has_live_token(self, tenant_id: str) -> bool: ...
    def tenant_for_token_hash(self, digest: str) -> tuple[str, str] | None: ...
    def delete_tenant(self, tenant_id: str) -> None: ...
